apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabel:
      app: nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: feeziman007/node-server:latest
        ports:
          - containerPort: 3000


  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-cloud-devops
  labels:
    app: capstone-project-cloud-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project-cloud-devops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project-cloud-devops
    spec:
      containers:
        - image: sabbir33/capstone-project-cloud-devops
          imagePullPolicy: Always
          name: capstone-project-cloud-devops
          ports:
            - containerPort: 80