apiVersion: v1
kind: Service
metadata:
  name: blue-service
  labels:
    app: udacity-capstone-project
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: udacity-capstone-project
    version: v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: udacity-capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: v1.0.0
  template:
    metadata:
      labels:
        app: udacity-capstone-project
        version: v1.0.0
    spec:
      containers:
      - name: capstone-docker-container-blue
        image: feeziman007/capstone-docker-image-blue
        ports:
        - name: http
          containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0