apiVersion: v1
kind: Service
metadata:
  name: green-service
  labels:
    app: udacity-capstone-project
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: udacity-capstone-project
    version: v2.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: udacity-capstone-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: v2.0.0
  template:
    metadata:
      labels:
        app: udacity-capstone-project
        version: v2.0.0
    spec:
      containers:
      - name: capstone-docker-container-green
        image: feeziman007/capstone-docker-image-green
        ports:
        - name: http
          containerPort: 80
        # - name: probe
        #   containerPort: 8086
        env:
        - name: VERSION
          value: v2.0.0
        # livenessProbe:
        #   httpGet:
        #     path: /live
        #     port: probe
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: probe
        #   periodSeconds: 5